version: 2
jobs:
  dev:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 28
      - run: date
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 12
workflows:
  version: 2
  one_and_two:
    jobs:
      - dev
      - test
